name: Export draw.io Diagrams

on:
  push:
    branches:
      - main
    paths:
      - '**/*.drawio'

jobs:
  export-drawio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Draw.io Export Action
        uses: rlespinasse/drawio-export-action@v2.24.0
        with:
          files: |
            src/Zepto/ZeptoLLD.drawio
          format: png

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated export of draw.io diagrams'
          file_pattern: src/Zepto/ZeptoLLD.png
