name: Export draw.io Diagrams

on:
  push:
    branches:
      - main  # Change if your default branch is different
    paths:
      - '**/*.drawio'

jobs:
  export-drawio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Export draw.io Diagrams to PNG
        uses: mxschmitt/action-drawio@v1
        with:
          files: |
            src/Zepto/ZeptoLLD.drawio
          format: png

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated export of draw.io diagrams'
          file_pattern: src/Zepto/ZeptoLLD.png
